services:
  db:
    image: postgres:16-alpine
    container_name: newsify
    environment:
      POSTGRES_DB: newsify-db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: adminpassword
    volumes:
      - newsify-db-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    restart: unless-stopped

volumes:
  newsify-db-data: