basePath: /v1
definitions:
  user.LoginUserRequest:
    properties:
      email:
        maxLength: 255
        type: string
      password:
        maxLength: 72
        minLength: 5
        type: string
    required:
    - email
    - password
    type: object
  user.LoginUserResponse:
    properties:
      access_token:
        type: string
      refresh_token:
        type: string
      user_id:
        type: integer
    type: object
  user.RefreshTokenRequest:
    properties:
      refresh_token:
        type: string
    required:
    - refresh_token
    type: object
  user.RefreshTokenResponse:
    properties:
      access_token:
        type: string
    type: object
  user.RegisterUserRequest:
    properties:
      email:
        maxLength: 255
        type: string
      password:
        maxLength: 72
        minLength: 5
        type: string
      role:
        enum:
        - reader
        - creator
        type: string
      username:
        maxLength: 100
        type: string
    required:
    - email
    - password
    - role
    - username
    type: object
  user.RegisterUserResponse:
    properties:
      email_id:
        type: string
      token:
        type: string
    type: object
  user.ResendOTPRequest:
    properties:
      email:
        maxLength: 255
        type: string
    required:
    - email
    type: object
  user.ResendOTPResponse:
    properties:
      email_id:
        type: string
    type: object
  user.VerifyUserRequest:
    properties:
      code:
        type: string
      email_id:
        type: string
      token:
        type: string
    required:
    - code
    - email_id
    - token
    type: object
  util.DataResponse:
    properties:
      data: {}
    type: object
  util.ErrorResponse:
    properties:
      error:
        type: string
    type: object
host: localhost
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: API for Newsify. An application for users to get latest news on a variety
    of topics.
  termsOfService: http://swagger.io/terms/
  title: Newsify API
paths:
  /authentication/{refreshToken}/logout:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token to revoke
        in: path
        name: refreshToken
        required: true
        type: string
      produces:
      - application/json
      responses:
        "204":
          description: No content
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Logout user
      tags:
      - authentication
  /authentication/login:
    post:
      consumes:
      - application/json
      parameters:
      - description: User login credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/user.LoginUserRequest'
      produces:
      - application/json
      responses:
        "200":
          description: User token
          schema:
            allOf:
            - $ref: '#/definitions/util.DataResponse'
            - properties:
                data:
                  $ref: '#/definitions/user.LoginUserResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: User login
      tags:
      - authentication
  /authentication/refresh:
    post:
      consumes:
      - application/json
      parameters:
      - description: Refresh token
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/user.RefreshTokenRequest'
      produces:
      - application/json
      responses:
        "200":
          description: New access token
          schema:
            allOf:
            - $ref: '#/definitions/util.DataResponse'
            - properties:
                data:
                  $ref: '#/definitions/user.RefreshTokenResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "401":
          description: Unauthorized
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Refresh access token
      tags:
      - authentication
  /authentication/register:
    post:
      consumes:
      - application/json
      parameters:
      - description: User credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/user.RegisterUserRequest'
      produces:
      - application/json
      responses:
        "201":
          description: User registration token
          schema:
            allOf:
            - $ref: '#/definitions/util.DataResponse'
            - properties:
                data:
                  $ref: '#/definitions/user.RegisterUserResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Registers a user
      tags:
      - authentication
  /authentication/resendOTP:
    post:
      consumes:
      - application/json
      parameters:
      - description: Resend OTP
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/user.ResendOTPRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OTP sent
          schema:
            allOf:
            - $ref: '#/definitions/util.DataResponse'
            - properties:
                data:
                  $ref: '#/definitions/user.ResendOTPResponse'
              type: object
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: Resend OTP
      tags:
      - authentication
  /authentication/verify:
    post:
      consumes:
      - application/json
      parameters:
      - description: User verification credentials
        in: body
        name: payload
        required: true
        schema:
          $ref: '#/definitions/user.VerifyUserRequest'
      produces:
      - application/json
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/util.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/util.ErrorResponse'
      summary: User verification
      tags:
      - authentication
  /health:
    get:
      description: Healthcheck endpoint
      produces:
      - application/json
      responses:
        "200":
          description: ok
          schema:
            type: string
      summary: Healthcheck
      tags:
      - ops
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: Authorization
    type: apiKey
swagger: "2.0"
